### ISSUE TITLE
Layout: Code

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#162]
**Blocks:**
- [x] code-reference-deprecated #167
- [x] code-reference-private-access #168 
- [x] code-reference-title  #171 
- [x] code-reference-summary [3732004](https://github.com/WordPress/wporg-developer/commit/37320043390ab206ec59cd7f6587f08433a53377)
- [x] code-reference-description (I don't think there's anything to do here.)
- [x] code-reference-parameters #173
- [x] code-reference-return-value #176
- [x] code-reference-explanation #177 
- [x] code-reference-source #172
- [x] code-reference-hooks #175
- [x] code-reference-related #170 
- [x] code-reference-changelog  https://github.com/WordPress/wporg-developer/commit/bdbaa48e713acf0de22e439e1e8e9db71f87aa70
- [x] code-reference-user-notes #178

**Blocks:**
- [x] Table of Contents

**Layout:**
- [x] Section heading styles. #190 
- [x] Fix layout from deprecated & private message https://github.com/WordPress/wporg-developer/commit/c3c2b1f732cf80a4624a2979f93e6850f38dc4fd
- [x] Add First Published/Last Update controls

## Screenshot

[Figma Link](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Pages?node-id=1160%3A10750&t=pS0XoTexhVvCl9Ft-0)

![image](https://user-images.githubusercontent.com/1657336/212214836-ccb481e4-7837-4c0d-bc8d-bdcc154b53e5.png)
